### ISSUE TITLE
ship test fails with NullPointerException and no other details

### ISSUE THREAD

**Issue by aspiers** [aergoio/ship#3]
I cloned https://github.com/aergoio/athena-370/ and got this error:

```
$ ship install aergoio/athena-343
Successful to install aergoio/athena-343.
Install path: /home/adam/.aergo_modules/aergoio/athena-343

$ ship test                      
 o src/test/lua/test-util.lua
nested exception is java.lang.NullPointerException
Unexpected exception!! Report the bug to support@aergo.io
```

I reported the bug to the email address, but I thought it would be worth reporting here too.  I think `ship` should show the details of the exception (e.g. stacktrace) so that we can debug it more easily.

**Comment by aspiers** [comment]
OK, I figured out that a) this happens with every single smart contract I try, and also I managed to get some debug by tweaking `assembly/build/distributions/ship-1.0-RC1/conf/ship-logger.xml` to include:

```
  <root level="DEBUG">
    <appender-ref ref="STDOUT" />
  </root>
```

Here is the result:

```
ship test                                                                         
16:46:35,888 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [/home/adam/Blocko/git/ship/assembly/build/distributions/ship-1.0-RC1/c
onf/ship-logger.xml] at [file:/home/adam/Blocko/git/ship/assembly/build/distributions/ship-1.0-RC1/conf/ship-logger.xml]
16:46:36,099 |-INFO in ch.qos.logback.core.joran.action.StatusListenerAction - Added status listener of type [ch.qos.logback.core.status.NopStatusListener]
16:46:36,099 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:46:36,118 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:46:36,294 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
16:46:36,294 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
16:46:36,294 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
16:46:36,296 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
16:46:36,296 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:46:36,297 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:46:36,300 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1fbc7afb - Registering current configuration as safe fallback point
16:46 INFO  s.e.ShipLauncher - Apm launched                     
16:46 DEBUG s.b.ResourceManager - src/test/lua/test-util.lua added                                                                                           
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@667a738 -> ship.build.Concatenator@667a738
16:46 DEBUG s.b.ResourceManager - src/main/lua/main.lua added
16:46 DEBUG s.b.Concatenator - Dependencies of TestResource@src/test/lua/test-util.lua(.): [PackageResource@/home/adam/.aergo_modules/aergoio/athena-343(/hom
e/adam/.aergo_modules/aergoio/athena-343), Source@src/main/lua/main.lua(.)]
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@667a738 -> ship.build.Concatenator@3bbc39f8
16:46 DEBUG s.b.ResourceManager - src/main/lua/main.lua added
16:46 DEBUG s.b.Concatenator - Dependencies of PackageResource@/home/adam/.aergo_modules/aergoio/athena-343(/home/adam/.aergo_modules/aergoio/athena-343): [S
ource@src/main/lua/main.lua(/home/adam/.aergo_modules/aergoio/athena-343)]
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@3bbc39f8 -> ship.build.Concatenator@3bbc39f8
16:46 DEBUG s.b.ResourceManager - src/main/lua/runner.lua added
16:46 DEBUG s.b.ResourceManager - src/main/lua/mockup.lua added
16:46 DEBUG s.b.ResourceManager - src/main/lua/assert.lua added
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/main.lua(/home/adam/.aergo_modules/aergoio/athena-343): [Source@src/main/lua/runner.lua(/h
ome/adam/.aergo_modules/aergoio/athena-343), Source@src/main/lua/mockup.lua(/home/adam/.aergo_modules/aergoio/athena-343), Source@src/main/lua/assert.lua(/ho
me/adam/.aergo_modules/aergoio/athena-343)]
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@3bbc39f8 -> ship.build.Concatenator@3bbc39f8
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/runner.lua(/home/adam/.aergo_modules/aergoio/athena-343): []
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@3bbc39f8 -> ship.build.Concatenator@3bbc39f8
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/mockup.lua(/home/adam/.aergo_modules/aergoio/athena-343): []
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@3bbc39f8 -> ship.build.Concatenator@3bbc39f8
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/assert.lua(/home/adam/.aergo_modules/aergoio/athena-343): []
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@667a738 -> ship.build.Concatenator@667a738
16:46 DEBUG s.b.ResourceManager - src/main/lua/mint.lua added
16:46 DEBUG s.b.ResourceManager - src/main/lua/balance.lua added
16:46 DEBUG s.b.ResourceManager - src/main/lua/history.lua added
16:46 DEBUG s.b.ResourceManager - src/main/lua/asset.lua added
16:46 DEBUG s.b.ResourceManager - src/main/lua/util.lua added
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/main.lua(.): [Source@src/main/lua/mint.lua(.), Source@src/main/lua/balance.lua(.), Source@
src/main/lua/history.lua(.), Source@src/main/lua/asset.lua(.), Source@src/main/lua/util.lua(.)]
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@667a738 -> ship.build.Concatenator@667a738
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/mint.lua(.): [Source@src/main/lua/util.lua(.)]
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@667a738 -> ship.build.Concatenator@667a738
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/util.lua(.): []
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@667a738 -> ship.build.Concatenator@667a738
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/balance.lua(.): [Source@src/main/lua/util.lua(.)]
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@667a738 -> ship.build.Concatenator@667a738
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/history.lua(.): [Source@src/main/lua/util.lua(.)]
16:46 DEBUG s.b.Concatenator - Resource manager changed: ship.build.Concatenator@667a738 -> ship.build.Concatenator@667a738
16:46 DEBUG s.b.Concatenator - Dependencies of Source@src/main/lua/asset.lua(.): []
16:46 DEBUG s.t.LuaRunner - Output: 
16:46 DEBUG s.c.TestProject - TestResultCollector: TestResultCollector(testFiles={src/test/lua/test-util.lua=ship.test.TestReportNode@2aece37d})
16:46 DEBUG s.u.AnsiMessagePrinter - Message:  <green>o</green> src/test/lua/test-util.lua
16:46 DEBUG s.u.AnsiMessagePrinter - ship.util.AnsiMessagePrinter$Normal@1a84f40f -> ship.util.AnsiMessagePrinter$TagOpen@23282c25
16:46 DEBUG s.u.AnsiMessagePrinter - ship.util.AnsiMessagePrinter$TagOpen@23282c25 -> ship.util.AnsiMessagePrinter$OpenColor@3b2da18f
16:46 DEBUG s.u.AnsiMessagePrinter - Tags: [green]
16:46 DEBUG s.u.AnsiMessagePrinter - ship.util.AnsiMessagePrinter$OpenColor@3b2da18f -> ship.util.AnsiMessagePrinter$Normal@5906ebcb
16:46 DEBUG s.u.AnsiMessagePrinter - ship.util.AnsiMessagePrinter$Normal@5906ebcb -> ship.util.AnsiMessagePrinter$TagOpen@258e2e41
16:46 DEBUG s.u.AnsiMessagePrinter - ship.util.AnsiMessagePrinter$TagOpen@258e2e41 -> ship.util.AnsiMessagePrinter$CloseColor@3d299e3
16:46 DEBUG s.u.AnsiMessagePrinter - Tags: []
16:46 DEBUG s.u.AnsiMessagePrinter - ship.util.AnsiMessagePrinter$CloseColor@3d299e3 -> ship.util.AnsiMessagePrinter$Normal@55a561cf
16:46 DEBUG s.u.AnsiMessagePrinter - State: ship.util.AnsiMessagePrinter$Normal@55a561cf
16:46 DEBUG s.u.AnsiMessagePrinter - Tags: []
 o src/test/lua/test-util.lua
nested exception is java.lang.NullPointerException
Unexpected exception!! Report the bug to support@aergo.io
16:46 DEBUG s.e.ShipLauncher - Unexpected exception: class java.lang.NullPointerException
java.lang.NullPointerException: null
        at ship.test.LuaRunner.run(LuaRunner.java:38)
        at ship.command.TestProject.executeTest(TestProject.java:92)
        at ship.command.TestProject.execute(TestProject.java:122)
        at ship.exec.ShipLauncher.execute(ShipLauncher.java:78)
        at java.util.Optional.ifPresent(Optional.java:159)
        at ship.exec.ShipLauncher.run(ShipLauncher.java:63)
        at ship.exec.ShipLauncher.main(ShipLauncher.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ship.ship.command.LaunchCommand.execute(LaunchCommand.java:20)
        at ship.exec.LoaderLauncher.run(LoaderLauncher.java:74)
        at ship.exec.LoaderLauncher.main(LoaderLauncher.java:32)
```

**Comment by aspiers** [comment]
Further debugging shows that `engine` assigned by

https://github.com/aergoio/ship/blob/f23b35451ff183d1c8fbac9cd9f7e8fd644e98de/core/src/main/java/ship/test/LuaRunner.java#L36

is `null`.

**Comment by aspiers** [comment]
I have just realised that this bug was caused by f2ae27587fef58e4562, which prevents the correct jars from getting onto the classpath.

**Comment by acktsap** [comment]
Fixed in https://github.com/aergoio/ship/pull/6
